# Generated by Django 4.2.4 on 2023-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_blogpost_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='desc',
            field=models.TextField(),
        ),
    ]
