# Generated by Django 4.2.4 on 2023-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blogpost_desc_blogpost_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='descriptions',
            field=models.TextField(default='nothing'),
        ),
    ]
