# Generated by Django 4.2.4 on 2023-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blogpost_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(upload_to='img'),
        ),
    ]
