# Generated by Django 4.2.4 on 2023-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blogpost_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pic',
        ),
    ]
